// src/components/Admin.vue
<template>
  <div class="container">
    <div class="content is-medium">
      <h1>
        Administrera fiskeresultat
      </h1>
      Här läggs resultat efter tävlingen in.
      <p></p>
      <form id="admin-form" @submit.prevent="processForm">
        <div class="field">
          <label class="label">År</label>
          <div class="control">
            <input
              id="year"
              class="input"
              type="text"
              placeholder="2020"
              v-model="participant.year"
            />
          </div>
        </div>
        <div class="field">
          <label class="label">Placering</label>
          <div class="control">
            <input
              id="place"
              class="input"
              type="text"
              placeholder="1"
              v-model="participant.place"
            />
          </div>
        </div>
        <div class="field">
          <label class="label">Namn</label>
          <div class="control">
            <input
              id="name"
              class="input"
              type="text"
              placeholder="Petra"
              v-model="participant.name"
            />
          </div>
        </div>
        <div class="field">
          <label class="label">Antal fiskar</label>
          <div class="control">
            <input
              id="score"
              class="input"
              type="text"
              placeholder="8"
              v-model="participant.score"
            />
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-link">Submit</button>
          </div>
          <div class="control">
            <button class="button is-link is-light">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
import { addParticipant } from "../CompetitionService";
export default {
  name: "Admin",
  el: "#admin-form",
  data: function() {
    return {
      participant: {
        year: "",
        place: "",
        name: "",
        score: ""
      }
    };
  },
  methods: {
    processForm: function() {
      addParticipant(this.participant);
    }
  }
};
</script>

// client/components/Admin.jsx
import React, { Component } from "react";
import { addParticipant } from "./CompetitionService.js"

class Admin extends React.Component {
    constructor(props) {
        super(props);
        this.state = { year: '', score: '' , name: '', place: ''};
        this.handleChanged = this.handleChanged.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }


    handleChanged(event) {

        if (event.target.id == 'score') {
            this.setState({ score: event.target.value });
        } else if (event.target.id == 'year') {
            this.setState({ year: event.target.value });
        } else if (event.target.id == 'place') {
            this.setState({ place: event.target.value });
        } else if (event.target.id == 'name') {
            this.setState({ name: event.target.value });
        }

    }

    handleSubmit(event) {
        alert('hur ser state ut??: ' + this.state.year + ',' + this.state.score + ',' + this.state.name + ',' + this.state.place);
        event.preventDefault();
        addParticipant(this.state);
    }

    render() {
        return (
            <div>


                <h2>Administrera fiskeresultat</h2>
                <p>Lägg in resultat efter tävlingen.</p>

                <div className="row">
                    <div className="col-sm-8 col-md-12 col-lg-12">

                        <form className="form-horizontal" role="form" onSubmit={this.handleSubmit}>
                            <div className="form-group">
                                <label className="control-label col-sm-2" htmlFor="year">År:</label>
                                <div className="col-sm-10">
                                    <input type="text" className="form-control" id="year" placeholder="År" value={this.state.year} onChange={this.handleChanged} />
                                </div>
                            </div>
                            <div className="form-group">
                                <label className="control-label col-sm-2" htmlFor="year">Placering:</label>
                                <div className="col-sm-10">
                                    <input type="text" className="form-control" id="place" placeholder="Placering" value={this.state.place} onChange={this.handleChanged} />
                                </div>
                            </div>
                            <div className="form-group">
                                <label className="control-label col-sm-2" htmlFor="name">Namn</label>
                                <div className="col-sm-10">
                                    <input type="text" className="form-control" id="name" placeholder="Namn" value={this.state.name} onChange={this.handleChanged} />
                                </div>
                            </div>
                            <div className="form-group">
                                <label className="control-label col-sm-2" htmlFor="score">Antal fiskar</label>
                                <div className="col-sm-10">
                                    <input type="text" className="form-control" id="score" placeholder="Antal fiskar" value={this.state.score} onChange={this.handleChanged} />
                                </div>
                            </div>
                            <div className="form-group">
                                <div className="col-sm-offset-2 col-sm-10">
                                    <input type="submit" className="btn btn-primary" value="Spara" />

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        );
    }
}

export default Admin
