// src/components/Competition.vue
<template>
  <div class="box">
    <div class="columns">
      <div class="column">
        <figure class="image is-ratio">
          <img
            :src="`images/group/group_${year}.jpg`"
            alt="Image"
            width="200px"
            height="100px"
          />
        </figure>
      </div>
      <div class="column content">
        <table class="table is-hoverable is-fullwidth is-striped">
          <thead>
            <tr>
              <th>Deltagare/Lag</th>
              <th>Poäng</th>
            </tr>
          </thead>
          <tbody>
            <tr :key="participant._id" v-for="participant in participants">
              <td>{{ participant.name }}</td>
              <td>{{ participant.score }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import { getParticipants } from "../CompetitionService";
export default {
  name: "Competition",
  data: function() {
    return {
      year: this.$route.params.year,
      participants: [
        {
          name: "",
          score: ""
        }
      ]
    };
  },

  created: function() {
    getParticipants(this.year).then(result => {
      this.participants = result.data;
    });
  }
};
</script>

// client/components/Competition.jsx

import React, { Component } from "react";
import { getParticipants } from "./CompetitionService.js"
import ReactImageFallback from "react-image-fallback";


class Competition extends React.Component {

  constructor() {
    super();
    this.state = { participants: [] };

  }

  componentDidMount() {
    getParticipants(this.props.match.params.year).then((result) => {
      let participants = Array.from(result.data);

      this.setState({ participants: participants });
    });
  }



  render() {
    return (
      <div>
        <div className="page-header">

          <h2>Resultat {this.props.match.params.year}</h2>
        </div>

        <div className="card" >
          <ReactImageFallback
            src={"./client/images/group/group_" + this.props.match.params.year + ".JPG"}
            fallbackImage="./client/images/other/DSC_0012.JPG"
            className="card-img-top" />
          <div className="card-body">
            <div className="card-text">
              <table className="table table-striped">
                <thead>
                  <tr>
                    <td>Deltagare/Lag</td>
                  </tr>
                </thead>
                <tbody>
                  {this.state.participants.map(participant => <Participant place={participant.place} score={participant.score} name={participant.name} key={participant.name} />)}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    );
  }

}



const Participant = (props) => {
  return (
    <tr>
      <td>
        {props.place}. {props.name}
      </td>
      <td>{props.score}p</td>
    </tr>
  );

}

export default Competition
